# Copyright 2020, Oracle Corporation and/or its affiliates.  All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.

domain-connections:
  - id: default
    name: domain1
    version: "14.1.1.0.0"
    username: weblogic
    listenAddress: localhost
    listenPort: 7001
    isDefault: true
  - id: rjrf_domain
    name: restricted_jrfDomain
    version: "14.1.1.0.0"
    username: weblogic
    listenAddress: localhost
    listenPort: 7101
    isDefault: false
