# Copyright 2020, 2021, Oracle Corporation and/or its affiliates.  All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.

perspectives:
  - id: configuration
    type: built-in
    iconFiles:
      light: navstrip-icon-readwrite-configuration-blk_48x48
      dark: navstrip-icon-readwrite-configuration-wht_48x48
      greyed: navstrip-icon-readwrite-configuration-gry_48x48
  - id: monitoring
    type: built-in
    iconFiles:
      light: navstrip-icon-monitoring-blk_48x48
      dark: navstrip-icon-monitoring-wht_48x48
      greyed: navstrip-icon-monitoring-gry_48x48
