# Copyright 2020, Oracle Corporation and/or its affiliates.  All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.

perspectives:
  - id: configuration
    label: Configuration
    description: "<p>Maintain configuration of WebLogic domain you are currently working with.</p>"
    type: built-in
    iconFiles:
      light: configuration-icon-navstrip-blk_48x48
      dark: configuration-icon-navstrip-wht_48x48
      greyed: configuration-icon-navstrip-gry_48x48
  - id: monitoring
    label: Monitoring
    description: "<p>View runtime MBean information for select resources in WebLogic domain you are currently working with.</p>"
    type: built-in
    iconFiles:
      light: monitoring-icon-navstrip-blk_48x48
      dark: monitoring-icon-navstrip-wht_48x48
      greyed: monitoring-icon-navstrip-gry_48x48
